name: Release

on:
  push:
    branches:
      - acc

jobs:
  release-module-version:
    uses: guidion-digital/release-workflows/.github/workflows/github-release-tag.yaml@v2
    with:
      branch: ${{ github.ref_name }}
    permissions:
      contents: write
